### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by qilicun** [egrcc/zhihu-python#1]
我在试用这个程序的时候，在config.ini里输入了自己的邮箱和密码，但是为什么总是显示登录失败？

**Comment by qilicun** [comment]
create_session()这个函数里面。

**Comment by egrcc** [comment]
估计是验证码的问题。因为知乎登录有时需要验证码，而create_session()里面模拟登录没有提交验证码，故登录失败。你先试试在浏览器中成功登录一下，然后退出，再登录时应该就不需要验证码了。（如果你开了代理或者不是常用地ip的话，可能还会要验证码）这时，再试试看，程序能否登录成功。（如果不成功的话，目前我也没有办法了）
其实后来我发现不用模拟登录也是可以获取所有信息的，只不过现在我没有时间修改代码，等放寒假了，我再把代码改一改。

**Comment by qilicun** [comment]
我尝试过先用账号在网页版登录，然后运行程序，好像还是不成功。如果有不需要登录的机制，可能会更好。

在 2015年1月8日 下午4:43，egrcc <notifications@github.com>写道：

**Comment by tiansh** [comment]
诶？不登录的情况下所有信息都可以抓到啊……
我有空也去看看……

08.01.2015, 16:43, "egrcc" <notifications@github.com>:
> 估计是验证码的问题。因为知乎登录有时需要验证码，而create_session()里面模拟登录没有提交验证码，故登录失败。你先试试在浏览器中成功登录一下，然后退出，再登录时应该就不需要验证码了。（如果你开了代理或者不是常用地ip的话，可能还会要验证码）这时，再试试看，程序能否登录成功。（如果不成功的话，目前我也没有办法了）
> 
> 其实后来我发现不用模拟登录也是可以获取所有信息的，只不过现在我没有时间修改代码，等放寒假了，我再把代码改一改。
> 
> —
> Reply to this email directly or view it on GitHub.

--

**Comment by Eureka22** [comment]
已解决
