### ISSUE TITLE
获取关注人数的时候脚本会自动停止

### ISSUE THREAD

**Issue by yannisxu** [egrcc/zhihu-python#25]
大概在获取 800 多名用户之后，脚本就会自动停止，也没有报错，后台运行状态似乎是正常的：

`root     10371  0.9 10.4 273236 52232 ?        Sl   09:35   6:23 python my_programe.py`

**Comment by egrcc** [comment]
抱歉，最近忙，可能无法及时处理了，大概要到国庆假期。

**Comment by yannisxu** [comment]
@egrcc  没事哈~我自己也再看看

**Comment by yannisxu** [comment]
关闭，暂时没遇到了..
