### ISSUE TITLE
数组越界了

### ISSUE THREAD

**Issue by ustczen** [egrcc/zhihu-python#26]
from zhihu import Question

url = "http://www.zhihu.com/question/35564122"
question = Question(url)
answers = question.get_all_answers()
for answer in answers:
    answer.to_txt()
    answer.to_md()
跑到一半提示越界了。

**Comment by mingrui** [comment]
我遇到相同的问题

**Comment by egrcc** [comment]
是的，知乎有些地方改了，各位发现了自行修改相应源代码就可以了

**Comment by mingrui** [comment]
thanks

**Comment by asin929** [comment]
zhihu.py中第196行
`if soup.find_all("h3", class_="zm-item-answer-author-wrap")[j].string == u"匿名用户":`
应改为
`if soup.find_all("h3", class_="zm-item-answer-author-wrap")[j].text.strip() == u"匿名用户":`
