### ISSUE TITLE
 Json decode失败---ayth.py

### ISSUE THREAD

**Issue by justkg** [egrcc/zhihu-python#30]
142 行的 `result = r.json()` 改成:

body = r.content
print body
result = json.loads(body)

可以正常登陆。
![78jph ve ckmmaxo4034wro](https://cloud.githubusercontent.com/assets/10934208/10867887/0305d014-80b5-11e5-9533-22252188e082.png)

**Comment by lichald** [comment]
#30 修正问题son decode失败---ayth.py #30
body = r.content
print body
result = json.loads(body.decode()) #这里面是bytes类型，要改成str再json转为dict

**Comment by LuoZijun** [comment]
@lichald `r.content` 为 raw http response body ( or request ) ，知乎默认响应为 UTF-8 编码。

由于我们的 Python 代码文件头部已经声明了 `utf8` 类型，json 包会按照我们代码脚本设定的 code 来进行解码，即 `r.content.decode()` ， 等于 `r.content.decode("utf8")`。

![7f6eab15-25fc-4d4b-ae4e-eee52dc7e464](https://cloud.githubusercontent.com/assets/717717/11371881/9ed8131e-9305-11e5-8d82-1267954b86b7.png)


假如你的代码文件编码不是 `utf8`  , 或者 知乎响应的 HTTP Response Body 内容编码不是 `utf8`（也可能是 `GB18030` ）  ， 那么直接写成 `r.content.decode()` 是不合适的。

比如知乎可能响应的是 `GB18030` 的编码 `\xce\xd2hi`，那么这个时候你使用 `r.content.decode()` 或者 `r.content.decode("utf8")` 是没用的。

碰到这种情况，我们可以使用 `chardet` 这个库来猜测 一串字符的编码（ `chardet.detect(r.content)` ）。

但是我们这里，由于事先已经知道知乎的响应编码是 `utf8`，我们的 代码脚本 也是 `utf8`。所以这一步就省略掉了。

![bb09f73f-6150-4b07-b83e-b24674620c17](https://cloud.githubusercontent.com/assets/717717/11371470/a1d0e692-9303-11e5-9597-d0da64a8e4ee.png)

**Comment by Kriscoco** [comment]
cmd环境下运行python auth.py总是出现："WARN:账号信息无效"，怎么解决？

**Comment by Kriscoco** [comment]
#Line 212, 213#
account  = raw_input("请输入登录帐号: ")
password = raw_input("请输入登录帐号: ")
建议改成：
account  = raw_input(unicode("请输入登录帐号: ", 'utf-8').encode('gbk'))
password = raw_input(unicode("请输入登录帐号: ", 'utf-8').encode('gbk'))
可以避免cmd运行中的乱码.

**Comment by LuoZijun** [comment]
@Kriscoco 这个不太好，你改成 GBK 输出了，那我们 OS X 和 Linux 用户怎么办？我们都是 UTF-8 ...

不过有两全方案就比较好了。

**Comment by egrcc** [comment]
@LuoZijun 可以在输出前先判断一下操作系统，再作相应的操作

**Comment by YaoZeyuan** [comment]
似乎可以通过sys.stdout.encoding获取系统当前编码，然后再进行译解
raw_input(unicode("请输入登录密码: ", 'utf-8').encode(sys.stdout.encoding)

**Comment by LuoZijun** [comment]
@egrcc @YaoZeyuan `sys.stdout.encoding ` 这个在 `windows` 下面工作正常吗？

**Comment by egrcc** [comment]
@LuoZijun sys.stdout.encoding 我没有用过，我在 zhihu.py 里都是用 platform.system() == 'Windows' 来判断系统是否是 windows，是的话就把编码转成 gbk 再输出

**Comment by LuoZijun** [comment]
@egrcc 测试了，是可以的。windows 10 下面的默认编码是 `CP936(GBK)`。

**Comment by LuoZijun** [comment]
@egrcc @YaoZeyuan @Kriscoco 默认的输出 一般都是 `print u" string ."`, 这样可以解决不同系统的差异，但是 `raw_input` 函数似乎不支持 `raw_input(u"Tips ..")` 这样，不过我找到一个解决办法，不需要去写复杂的 `encoding/decoding`，我们只需使用 系统默认的基本输入输出来打印 提示符即可：

```python
# 原来
account  = raw_input("请输入登录帐号: ")
password = raw_input("请输入登录密码: ")

# 修改
import sys
sys.stdout.write(u"请输入登录账号: ")
account  = raw_input()
sys.stdout.write(u"请输入登录密码: ")
password = raw_input()
```
