### ISSUE TITLE
获取用户活动信息(JSon数据)时返回403，您是如何处理的？

### ISSUE THREAD

**Issue by wut0n9** [egrcc/zhihu-python#33]
当我想获取知乎用户活动信息时，在登录状态下使用post方法向http://www.zhihu.com/people/yunshu/activities 后台提交start和_xsrf表单字段后，结果响应返回403，而在非登录条件下，能够获取用户前十条信息，请问，如何处理能够获取正常的JSon数据？（也即是如何获取用户更多的最新状态数据？）

**Comment by egrcc** [comment]
post的时候带上header没有?

**Comment by wut0n9** [comment]
这里请求header：
postheader = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36',
    'X-Requested-With': 'XMLHttpRequest',
    'Referer': 'http://www.zhihu.com/people/yunshu',
    'Origin': 'http://www.zhihu.com',
    'Host': 'www.zhihu.com',
    'DNT': 1,
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'Content-Length': 55,
    'Connection': 'keep-alive',
    'Accept-Language': 'zh-CN,zh;q=0.8,en;q=0.6',
    'Accept-Encoding': 'gzip, deflate',
    'Accept': '*/*',
}
这是Cookies字段：
cookies = {
        'cap_id': r.cookies['cap_id'],
        'n_c': r.cookies['n_c'],
        'q_c1': r.cookies['q_c1'],
        '_xsrf': r.cookies['_xsrf'],
        '__utma':  '51854390.718044998.1437968009.1438008067.1438170721.3',
        '__utmv':  '51854390.100-1|2=registration_date=20140316=1^3=entry_date=20140316=1',
        '__utmz':  '51854390.1438170721.3.3.utmcsr=suche.web.de|utmccn=(referral)|utmcmd=referral|utmcct=/web',
      '_za':  'a2acfac3-1367-4848-af1c-3be6b11135c9',
    }
这是post方法向http://www.zhihu.com/people/yunshu/activities 提交的表单：
payload = {
                'start': data_time_next_url,  # data_time_next_url,
                '_xsrf': xsrf,
            }
使用这些数据后，发现向服务器发送数据的请求头部有重复字段，如‘q_c1’、'cap_id'、 '_xsrf'字段，是因为多次请求都使用了cookies关键字？如：r2 = sessionObj.get('http://www.zhihu.com/captcha.gif', headers=headers, cookies=cookies, timeout=10)  [其中sessionObj=requests.Session()]。我不是很清楚cookie中的 '__utma'、 '__utmv'、'__utmz'字段是不是固定值，写的程序代码没能获取到，上面这些值是从浏览器中直接拷过来的。即便这些字段 '__utma'、 '__utmv'、'__utmz'不写，也能够获取到非JSon数据。

**Comment by LuoZijun** [comment]
说明你的会话不是 合法的呗，直接使用 request.session 来做请求吧，这样不需要去手动管理 Cookies 这些会话信息。
如果你要检查这个 请求有没有用，打开知乎的页面，然后打开浏览器控制台，执行JavaScript 代码:

```JavaScript
var xsrf = $('input[name=\"_xsrf\"]').val();
var post_data = {"_xsrf": xsrf};
response = $.ajax({"url": "/people/luo-zi-jun/activities", "type": "POST", "data": post_data })
console.log(response.responseJSON);

```
