### ISSUE TITLE
Some changes to get test.py working

### ISSUE THREAD

**Issue by Thinkerinhell** [egrcc/zhihu-python#34]
Hi,
First of all, really appreciate for all the effort to make such a fantastic python crawl for ZhiHu.  
But there are some error when I tried to run test.py after cloned. 
I made the following to changes to get it to work.  

1. in auth.py,
def islogin():
    url = "http://www.zhihu.com/settings/profile" 
-- change to 
url = "https://www.zhihu.com/settings/profile" 

2. I think zhihu change some html tag :  in zhihu.py
change from
soup.find("h3", class_="zm-item-answer-author-wrap")
to
soup.find("div", class_="zm-item-answer-author-info")

3. change class user
from
elif user_url[0:28] != "https://www.zhihu.com/people/"
to
elif user_url.startswith('www.zhihu.com/people', user_url.index('//')+2) == False

Then everything works fine.

Thanks again for such a brilliant work

Cheers.

**Comment by closears** [comment]
@Thinkerinhell 3Q very much! I've been working on this for a few days but I failed:(

**Comment by egrcc** [comment]
@Thinkerinhell  Thanks for your comment!
