### ISSUE TITLE
执行过auth.py了import时还是报错

### ISSUE THREAD

**Issue by AlllenShen** [egrcc/zhihu-python#43]
在项目目录下执行auth.py 显示登陆成功
在自己的项目代码中import zhihu显示未登录
再次运行auth.py显示登陆过了

**Comment by kevinusable** [comment]
应该是运行auth.py时，登录成功后保存的cookies不完整。
我按照源代码运行的话，发现cookies文件里面没有_xsrf相关的属性。
修改下源代码里面的requests.cookies.save(**ignore_discard=True**)就可以了

**Comment by egrcc** [comment]
能把运行截图贴一下吗？test.py 能运行吗？

**Comment by Altriaex** [comment]
我遇到了相同的错误，这看起来是requests载入cookies时的路径问题。推测在import时request会在import语句所在文件的目录中寻找cookies，把载入cookies语句更改一下就好了。

将 zhihu.py line 84 和 auth.py line 11 更改为
requests.cookies = cookielib.LWPCookieJar(os.path.join(os.path.dirname(os.path.abspath(__file__)),'cookies'))
即可。
