### ISSUE TITLE
数组越界

### ISSUE THREAD

**Issue by Altriaex** [egrcc/zhihu-python#44]
seed =Question("https://www.zhihu.com/question/26746768")
allTheAnswers = [i for i in seed.get_all_answers()]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "zhihu.py", line 188, in get_all_answers
    if soup.find_all("div", class_="zm-item-answer")[j].find("span", class_="count") == None:
IndexError: list index out of range

**Comment by knarfeh** [comment]
我看了一下源代码，这个是因为打开的页面只能看到20个答案：
<img width="677" alt="more" src="https://cloud.githubusercontent.com/assets/6964284/12866469/3b5cb2e8-cd09-11e5-9c04-cc65de2551dc.png">
其实可以用这种方式打开：https://www.zhihu.com/question/40132462?sort=created&nr=1&page=1
先爬取有多少个答案，根据答案数量确定page数，然后爬每一页，这样就可以把所有的答案爬取下来，想改来着，但是不太明白get_all_answers函数中这段代码
```
for i in xrange((answers_num - 1) / 50 + 1):
                if i == 0:
                    for j in xrange(min(answers_num, 50)):
                        if self.soup == None:
                            self.parser()
                        soup = BeautifulSoup(self.soup.encode("utf-8"))
```
的意义。。

**Comment by egrcc** [comment]
知乎以前一次是加载50个答案的，现在改成20了，把代码里的50改成20就可以了

**Comment by knarfeh** [comment]
原来是这样，我脑袋里完全是另一段代码。。。。。。不好意思:sweat_smile:
