### ISSUE TITLE
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by luooly** [egrcc/zhihu-python#45]
python auth.py 
无法登录 ~ 
求解~ 
thx~

**Comment by luooly** [comment]
解决了！  将islogin中URL 的https 改成 http 搞定 。。。

**Comment by luooly** [comment]
又蹦了 。。

**Comment by egrcc** [comment]
此问题在我的机器上无法重现，参照这个链接试试看？http://stackoverflow.com/questions/10667960/python-requests-throwing-up-sslerror

**Comment by luooly** [comment]
![bug](https://cloud.githubusercontent.com/assets/15340007/13772270/31199390-eace-11e5-9e71-d527803b5751.png)
运行结果，是这样 我如果把 allow_redirects改为 verify 会显现登录成功。
但是接着运行test.py会显示未登录。
我用在win 系统python shell 运行 islogin（） 返回 302 没错的
上面测试实在 ubuntu 14.04 python 2.7.6
 求解决~ thx~

**Comment by egrcc** [comment]
楼上请参照https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484

**Comment by luooly** [comment]
谢谢 @egrcc  搞定了 ~ 
初学者 多谢耐心指点
