### ISSUE TITLE
登录模块用requests中的Session()来做应该会更方便

### ISSUE THREAD

**Issue by sunchenglu** [egrcc/zhihu-python#46]
个人建议，登录可以用requests.Session()做，这样都不必输入验证码，还是挺方便的
_xsrf 可以在登录页面中解析出来
伪代码：
s = requests.Session()
post_data = {'username':'','password':''}
post_data['_xsrf'] = _xsrf
post_data['remember_me'] = 'true'
login_rspn = self.s.post(LOGIN_URL,headers=HEADERS,data=post_data,timeout=10,verify=False)

之后用s中就会保存登录信息了
用s.get()发情求就行

**Comment by egrcc** [comment]
之前的版本中就是这样做的，（可见https://github.com/egrcc/zhihu-python/blob/prev/zhihu.py  create_session() 这个函数）只不过当时登录中还没有 _xsrf 这个参数。这样做在有些时候会有问题，比如知乎判断你登录异常时，还是会要你输入验证码，这样就会导致登录失败。可见 #1  #2  #5

**Comment by sunchenglu** [comment]
嗯嗯，明白了，多谢！
