### ISSUE TITLE
importError:no module named termcolor

### ISSUE THREAD

**Issue by KEVINLEE315** [egrcc/zhihu-python#47]
已经安装了termcolor，为什么运行auth.py的时候还是报错了。
![image](https://cloud.githubusercontent.com/assets/9585237/13415475/31ec17a4-df96-11e5-87a2-079953ff42b2.png)

**Comment by egrcc** [comment]
有点奇怪。。那你先试试在python环境中，import termcolor 看行不行？

**Comment by KEVINLEE315** [comment]
试过了，也是报错。而且我尝试重新安装termcolor，提示说系统已经安装过了。后来又在window系统试了，也是一样的错误

**Comment by KEVINLEE315** [comment]
我换了一台电脑试了，终于可以了。可能是我之前的电脑环境什么的有问题吧……
