### ISSUE TITLE
登录失败...

### ISSUE THREAD

**Issue by QhelDIV** [egrcc/zhihu-python#5]
@egrcc 同样的环境(ubuntu14.04 python2.76 firefox)，用户名密码cookies都写了但是怎么都是Login Failed 请填写验证码。。

**Comment by Eureka22** [comment]
可能是cookies有问题，需要将你浏览器登录知乎之后，访问知乎时的所有cookies都放进去。
- Following this issue.

**Comment by QhelDIV** [comment]
仔细检查了N遍都没问题怎么都是登陆失败= =...
索性新注册了一个号，马上就登录成功了= =...

**Comment by egrcc** [comment]
可能readme上没有说清楚，显示 ”Login Failed 请填写验证码“ 只是代表用 用户名，密码登录时由于未填写验证码而登录失败，并不代表用cookies模拟登录也会失败，所以请放心继续操作。后面应该会有”Use cookies“输出，代表后续的一些操作都会使用cookies，如果cookies填对的话，后面应该不会出现问题。
