### ISSUE TITLE
有一次commit中泄露了账户名和密码

### ISSUE THREAD

**Issue by Eureka22** [egrcc/zhihu-python#6]
Hi Lujun Zhao, 

你的有一次commit中的config.ini中泄露了账户名和密码，希望不会给你造成麻烦。

**Comment by egrcc** [comment]
没事，那是我用来测试的小号。那你知道用什么办法撤销这次记录吗？

**Comment by Eureka22** [comment]
可以在本地回滚到以前版本 再push，不过既然没事的话也可以不管，略麻烦…



Regards,
Fei

**Comment by LuoZijun** [comment]
建议目前可以考虑删除此配置文件，以免出现类似问题。
这个文件用户自行创建。
