### ISSUE TITLE
最近忙毕业论文，issue 和 pull requests 要过段时间才会处理

### ISSUE THREAD

**Issue by egrcc** [egrcc/zhihu-python#63]
我是项目作者，最近忙毕业论文，除一些紧急情况外，issue 和 pull requests 要过段时间才会处理。望各位理解。

**Comment by jiahillegass** [comment]
Are you undergraduate in China?
You are greate but there are really so many bugs i have met.
Can you offer me some links on how to deal with python web because i have some requirements in zhihu.
You can use chinese or gmail me @jiahillegass.gmail.com.
By the way, i am newer here,thks in advance.
